### PR TITLE
improvement of path

### PR DESCRIPTION
**Pull request by MTKouchoanou**
Hello 
dear instead of absolute path i have put relative path to avoid  file not exist exception

### CODE REVIEW

**Comment by TKouchoanou** [comment]
Thank you , i will check your modification and  accept or reject tomorrow

**Comment by MTKouchoanou** [comment]
ok no problem

**Comment by TKouchoanou** [comment]
Nice

**Comment by MTKouchoanou** [comment]
Nice too

**Comment by TKouchoanou** [comment]
I checked and you are right

**Comment by MTKouchoanou** [comment]
absolutely

**Comment by TKouchoanou** [comment]
I have done the merge

**Comment by MTKouchoanou** [comment]
Nice thank

**Comment by TKouchoanou** [comment]
Thanks you soo

**Pull request merged**
